export { default as Navbar } from './Navbar';
export {default as Feed } from './Feed';
export { default as Popular } from './Popular';
export { default as Search } from './Search';
export { default as SearchBar } from './SearchBar';
export { default as SideBar } from './SideBar';
export { default as Videos } from './Videos';
export { default as VideoCard } from './VideoCard';
export { default as AnimeDetail } from './AnimeDetail';
export { default as VideoDetail } from './VideoDetail';
export { default as DetailCard } from './DetailCard';
export { default as Footer } from './Footer';
export { default as EpisodeList } from './EpisodeList';
export { default as RelatedVideos } from './RelatedVideos';